def parse_list_file(file_path):
    exclusion_dict = {}
    current_section = None

    with open(file_path, 'r') as file:
        for line in file:
            line = line.strip()  # Remove any leading/trailing whitespace

            if not line or line.startswith('-------------'):  # Skip empty lines or separator lines
                continue

            # Check for section header (e.g., "themes/astra:")
            if line.endswith(':'):
                current_section = line[:-1]  # Remove the colon to get the section name
                exclusion_dict[current_section] = []  # Initialize list for this section

            elif current_section:
                # Add script IDs/paths under the current section
                exclusion_dict[current_section].append(line)

    return exclusion_dict


def export_to_python_file(exclusion_dict, output_file):
    with open(output_file, 'w') as file:
        file.write("# This file was generated by a script\n")
        file.write("exclusion_list = {\n")

        for section, scripts in exclusion_dict.items():
            file.write(f"    '{section}': [\n")
            for script in scripts:
                file.write(f"        '{script}',\n")
            file.write("    ],\n")

        file.write("}\n")


# Main script
file_path = 'list.txt'  # Path to your list.txt file
output_file = 'exclusion_new.py'  # Output Python file

# Parse the list file and generate the dictionary
exclusion_dict = parse_list_file(file_path)

# Export the dictionary to exclusion_new.py
export_to_python_file(exclusion_dict, output_file)

print(f"Exclusion list successfully exported to {output_file}")

